name: Binance Top Trader Monitor

on:
  schedule:
    # 30분마다 실행 (UTC 기준)
    - cron: '*/30 * * * *'
  workflow_dispatch: # 수동 실행도 가능

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip list  # 설치된 패키지 확인
        
    - name: Debug environment
      run: |
        echo "Python version:"
        python --version
        echo "Current directory:"
        pwd
        echo "Files in directory:"
        ls -la
        echo "Environment variables (filtered):"
        env | grep -E "(MIN_VOLUME|SYMBOLS_LIMIT)" || echo "No custom env vars found"
        
    - name: Run Top Trader Monitor
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        MIN_VOLUME_USD: ${{ vars.MIN_VOLUME_USD || '5000000' }}
        SYMBOLS_LIMIT: ${{ vars.SYMBOLS_LIMIT || '200' }}
      run: |
        python binance_top_trader_monitor_github.py
        
    - name: Upload logs on failure
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: error-logs
        path: |
          *.log
          *.txt
